Repository immichFrame/ImmichFrame, pull requests merged in 2024-08, with the labels that each got.

#101 Reverting version of Microsoft.Extensions.ApiDescription.Client and NSwag.ApiDescription.Client packages.
  ImmichFrame/ImmichFrame.csproj
Labels: fix

#106 Add note about UID from URL to README.md
  README.md
Labels: documentation

#108 Add current weather image next to temperature
  ImmichFrame/Helpers/ImageHelper.cs
  ImmichFrame/ViewModels/MainViewModel.cs
  ImmichFrame/Views/MainView.axaml
Labels: enhancement

#110 Add image stretch options Closes #103
  ImmichFrame/Models/Settings.cs
  ImmichFrame/ViewModels/MainViewModel.cs
  ImmichFrame/ViewModels/SettingsViewModel.cs
  ImmichFrame/Views/MainView.axaml
  ImmichFrame/Views/SettingsView.axaml
Labels: enhancement

#111 feat: Exclude albums option & exclude videos
  ImmichFrame/Helpers/AssetHelper.cs
  ImmichFrame/Models/Settings.cs
  ImmichFrame/Settings.example.json
  ImmichFrame/ViewModels/SettingsViewModel.cs
  ImmichFrame/Views/SettingsView.axaml
Labels: enhancement

#112 feat: Adding UnattendedMode setting to enable auto-continue on ErrorView.
  ImmichFrame/Models/Settings.cs
  ImmichFrame/ViewModels/MainViewModel.cs
Labels: enhancement

#115 - Highlight required settings with red border (if blank). - Avalonia update
  ImmichFrame.Android/ImmichFrame.Android.csproj
  ImmichFrame.Desktop/ImmichFrame.Desktop.csproj
  ImmichFrame/ImmichFrame.csproj
  ImmichFrame/ViewModels/SettingsViewModel.cs
  ImmichFrame/Views/SettingsView.axaml
  ImmichFrame/Views/SettingsView.axaml.cs
Labels: enhancement

#114 State display & ISO 3166 Abbreviations
  ImmichFrame/Helpers/LocationHelper.cs
  ImmichFrame/Models/Settings.cs
  ImmichFrame/ViewModels/MainViewModel.cs
  ImmichFrame/Views/SettingsView.axaml
Labels: enhancement

#118 Add Settings screen expanders and organize settings under them
  ImmichFrame/Views/SettingsView.axaml
  ImmichFrame/Views/SettingsView.axaml.cs
Labels: enhancement

#119 Show settings page instead of error message when settings not found.
  ImmichFrame.Android/ImmichFrame.Android.csproj
  ImmichFrame.Android/MainActivity.cs
  ImmichFrame.Desktop/ImmichFrame.Desktop.csproj
  ImmichFrame/ImmichFrame.csproj
  ImmichFrame/ViewModels/MainWindowViewModel.cs
  ImmichFrame/ViewModels/SettingsViewModel.cs
  ImmichFrame/Views/ErrorView.axaml.cs
  ImmichFrame/Views/SettingsView.axaml
Labels: enhancement

#121 Directly use Settings.CurrentSettings
  ImmichFrame/Helpers/AssetHelper.cs
  ImmichFrame/Helpers/LocationHelper.cs
  ImmichFrame/Helpers/WeatherHelper.cs
  ImmichFrame/Models/AssetResponseDto.cs
  ImmichFrame/Models/Settings.cs
  ImmichFrame/ViewModels/SettingsViewModel.cs
Labels: maintenance

#122 Nicer weather icons loaded from assets instead of http requests
  ImmichFrame/Assets/WeatherIcons/01d.png
  ImmichFrame/Assets/WeatherIcons/01n.png
  ImmichFrame/Assets/WeatherIcons/02d.png
  ImmichFrame/Assets/WeatherIcons/02n.png
  ImmichFrame/Assets/WeatherIcons/03d.png
  ImmichFrame/Assets/WeatherIcons/03n.png
  ImmichFrame/Assets/WeatherIcons/04d.png
  ImmichFrame/Assets/WeatherIcons/04n.png
  ImmichFrame/Assets/WeatherIcons/09d.png
  ImmichFrame/Assets/WeatherIcons/09n.png
  ImmichFrame/Assets/WeatherIcons/10d.png
  ImmichFrame/Assets/WeatherIcons/10n.png
  ImmichFrame/Assets/WeatherIcons/11d.png
  ImmichFrame/Assets/WeatherIcons/11n.png
  ImmichFrame/Assets/WeatherIcons/13d.png
  ImmichFrame/Assets/WeatherIcons/13n.png
  ImmichFrame/Assets/WeatherIcons/50d.png
  ImmichFrame/Assets/WeatherIcons/50n.png
  ImmichFrame/Assets/WeatherIcons/default.png
  ImmichFrame/ViewModels/MainViewModel.cs
  ImmichFrame/Views/MainView.axaml
Labels: enhancement

#107 Welcome page
  ImmichFrame/Models/Settings.cs
  ImmichFrame/ViewModels/ErrorViewModel.cs
  ImmichFrame/ViewModels/MainWindowViewModel.cs
  ImmichFrame/ViewModels/WelcomeViewModel.cs
  ImmichFrame/Views/WelcomeView.axaml
  ImmichFrame/Views/WelcomeView.axaml.cs
Labels: enhancement

#124 Add configurable refresh interval for Albums and People. Closes #123
  ImmichFrame/Helpers/AssetHelper.cs
  ImmichFrame/Models/Settings.cs
  ImmichFrame/Settings.example.json
  ImmichFrame/Views/SettingsView.axaml
Labels: enhancement

#125 Update README with Google Play Store link and formatting
  README.md
Labels: documentation
