Repository immichFrame/ImmichFrame, pull requests merged in 2024-04, with the labels that each got.

#48 Android support
  ImmichFrame.Android/ImmichFrame.Android.csproj
  ImmichFrame.Android/MainActivity.cs
  ImmichFrame.Android/Properties/AndroidManifest.xml
  ImmichFrame.Android/Resources/drawable/Immich.png
  ImmichFrame.Android/Resources/values-night/colors.xml
  ImmichFrame.Android/Resources/values/colors.xml
  ImmichFrame.Android/Resources/values/styles.xml
  ImmichFrame/App.axaml
  ImmichFrame/App.axaml.cs
  ImmichFrame/App.config
  ImmichFrame/Helpers/AssetHelper.cs
  ImmichFrame/Helpers/PlatformDetector.cs
  ImmichFrame/Helpers/RelayCommand.cs
  ImmichFrame/ImmichFrame.csproj
  ImmichFrame/ImmichFrame.sln
  ImmichFrame/Models/AssetResponseDto.cs
  ImmichFrame/Models/Settings.cs
  ImmichFrame/Properties/Settings.Designer.cs
  ImmichFrame/Properties/Settings.settings
  ImmichFrame/ViewModels/MainViewModel.cs
  ImmichFrame/ViewModels/MainWindowViewModel.cs
  ImmichFrame/ViewModels/SettingsViewModel.cs
  ImmichFrame/ViewModels/ViewModelBase.cs
  ImmichFrame/Views/MainView.axaml
  ImmichFrame/Views/MainView.axaml.cs
  ImmichFrame/Views/MainWindow.axaml
  ImmichFrame/Views/MainWindow.axaml.cs
  ImmichFrame/Views/SettingsView.axaml
  ImmichFrame/Views/SettingsView.axaml.cs
  ImmichFrame/Views/ViewLocaltor.cs
  ImmichFrame/Views/WindowView.axaml
  ImmichFrame/Views/WindowView.axaml.cs
Labels: enhancement

#50 Better API error messages
  ImmichFrame/Helpers/AssetHelper.cs
Labels: fix

#52 Remove old weather api and replace with openweathermap
  ImmichFrame/App.config
  ImmichFrame/Helpers/WeatherHelper.cs
  ImmichFrame/ImmichFrame.csproj
  ImmichFrame/Models/Settings.cs
  ImmichFrame/Properties/Settings.Designer.cs
  ImmichFrame/Properties/Settings.settings
  ImmichFrame/Settings.example.xml
  ImmichFrame/Views/MainView.axaml.cs
  ImmichFrame/Views/SettingsView.axaml
  ImmichFrame/Weather.cs
  ImmichFrame/WmoWeatherInterpreter.cs
Labels: enhancement

#54 Handle assets without a thumbnail / thumb hash
  ImmichFrame/Helpers/AssetHelper.cs
  ImmichFrame/Models/AssetResponseDto.cs
  ImmichFrame/ViewModels/MainViewModel.cs
Labels: fix

#51 Android build
  ImmichFrame/App.config
  ImmichFrame/Helpers/RelayCommand.cs
  ImmichFrame/Helpers/WeatherHelper.cs
  ImmichFrame/Models/AssetResponseDto.cs
  ImmichFrame/Models/Settings.cs
  ImmichFrame/Models/UiImage.cs
  ImmichFrame/Properties/Settings.Designer.cs
  ImmichFrame/Properties/Settings.settings
  ImmichFrame/ViewModels/MainViewModel.cs
  ImmichFrame/ViewModels/MainWindowViewModel.cs
  ImmichFrame/ViewModels/SettingsViewModel.cs
  ImmichFrame/ViewModels/ViewModelBase.cs
  ImmichFrame/Views/BaseView.cs
  ImmichFrame/Views/MainView.axaml
  ImmichFrame/Views/MainView.axaml.cs
  ImmichFrame/Views/SettingsView.axaml
  ImmichFrame/Views/SettingsView.axaml.cs
  ImmichFrame/Views/WindowView.axaml.cs
Labels: enhancement

#55 Weather fixes/changes
  ImmichFrame/Helpers/WeatherHelper.cs
  ImmichFrame/Models/AssetResponseDto.cs
  ImmichFrame/Models/Settings.cs
  ImmichFrame/ViewModels/SettingsViewModel.cs
  ImmichFrame/Views/MainView.axaml.cs
  ImmichFrame/Views/SettingsView.axaml
Labels: fix

#57 Refactor MainView
  ImmichFrame/Settings.example.xml
  ImmichFrame/ViewModels/MainViewModel.cs
  ImmichFrame/ViewModels/MainWindowViewModel.cs
  ImmichFrame/ViewModels/ViewModelBase.cs
  ImmichFrame/Views/BaseView.cs
  ImmichFrame/Views/MainView.axaml
  ImmichFrame/Views/MainView.axaml.cs
Labels: maintenance

#59 Versioning on Android and Desktop projects. Updated Readme for new features.
  ImmichFrame.Android/Properties/AndroidManifest.xml
  ImmichFrame.Desktop/ImmichFrame.Desktop.csproj
  README.md
Labels: maintenance

#62 Interactive Control, Settings Quit button
  ImmichFrame/ViewModels/MainViewModel.cs
  ImmichFrame/ViewModels/SettingsViewModel.cs
  ImmichFrame/Views/MainView.axaml
  ImmichFrame/Views/SettingsView.axaml
Labels: enhancement
