Repository immichFrame/ImmichFrame, pull requests merged in 2025-05, with the labels that each got.

#323 fix: Add text shadow to weather data display
  immichFrame.Web/src/lib/components/elements/clock.svelte
Labels: fix

#325 doc: Basic documentation Page
  docs/docs/contribute/Setup.md
  docs/docs/contribute/_category_.json
  docs/docs/demo.md
  docs/docs/getting-started/_category_.json
  docs/docs/getting-started/apps.md
  docs/docs/getting-started/configuration.md
  docs/docs/getting-started/installation/_category_.json
  docs/docs/getting-started/installation/docker.md
  docs/docs/getting-started/installation/prerequisites.md
  docs/docs/getting-started/setup.md
  docs/docs/overview.md
  docs/docusaurus.config.ts
Labels: documentation

#317 Feat: Rework Backend, decouple
  ImmichFrame.Core/Api/ImmichApi.cs
  ImmichFrame.Core/Helpers/ApiCache.cs
  ImmichFrame.Core/Helpers/ImmichFrameExtensionMethods.cs
  ImmichFrame.Core/Helpers/WebhookHelper.cs
  ImmichFrame.Core/Interfaces/IAppointmentService.cs
  ImmichFrame.Core/Interfaces/IImmichFrameLogic.cs
  ImmichFrame.Core/Interfaces/IWeatherService.cs
  ImmichFrame.Core/Logic/ImmichFrameLogic.cs
  ImmichFrame.Core/Logic/OptimizedImmichFrameLogic.cs
  ImmichFrame.Core/Services/IcalCalendarService.cs
  ImmichFrame.Core/Services/OpenWeatherMapService.cs
  ImmichFrame.WebApi/Controllers/AssetController.cs
  ImmichFrame.WebApi/Controllers/CalendarController.cs
  ImmichFrame.WebApi/Controllers/ConfigController.cs
  ImmichFrame.WebApi/Controllers/WeatherController.cs
  ImmichFrame.WebApi/Program.cs
  immichFrame.Web/src/lib/immichFrameApi.ts
Labels: enhancement

#332 Update README and link to new documentation
  README.md
Labels: documentation

#339 Feat: Fetch asset metadata for images without people
  immichFrame.Web/src/lib/components/home-page/home-page.svelte
Labels: enhancement

#338 Fix: Description for memory assets (x years ago)
  ImmichFrame.Core/Api/AssetResponseDto.cs
  ImmichFrame.Core/Logic/ImmichFrameLogic.cs
  ImmichFrame.Core/Logic/OptimizedImmichFrameLogic.cs
Labels: fix

#342 Fix: Logo flickering
  immichFrame.Web/src/lib/components/elements/image-component.svelte
Labels: bug

#350 Fix: Clock update
  immichFrame.Web/src/lib/components/elements/clock.svelte
Labels: fix

#344 Feat: Image Rework
  immichFrame.Web/src/lib/components/elements/asset-info.svelte
  immichFrame.Web/src/lib/components/elements/image-component.svelte
  immichFrame.Web/src/lib/components/elements/image.svelte
  immichFrame.Web/src/lib/components/home-page/home-page.svelte
Labels: enhancement

#354 Feat: Display album names
  ImmichFrame.Core/Interfaces/IClientSettings.cs
  ImmichFrame.Core/Interfaces/IImmichFrameLogic.cs
  ImmichFrame.Core/Logic/ImmichFrameLogic.cs
  ImmichFrame.Core/Logic/OptimizedImmichFrameLogic.cs
  ImmichFrame.WebApi/Controllers/AssetController.cs
  ImmichFrame.WebApi/Models/WebClientSettings.cs
  Install_Web.md
  docker/Settings.example.json
  docker/example.env
  docs/docs/getting-started/configuration.md
  docs/docs/getting-started/installation/docker.md
  immichFrame.Web/src/lib/components/elements/asset-info.svelte
  immichFrame.Web/src/lib/components/elements/image-component.svelte
  immichFrame.Web/src/lib/components/elements/image.svelte
  immichFrame.Web/src/lib/components/home-page/home-page.svelte
  immichFrame.Web/src/lib/immichFrameApi.ts
Labels: enhancement

#356 Feat: Display more details
  ImmichFrame.Core/Interfaces/IClientSettings.cs
  ImmichFrame.WebApi/Models/WebClientSettings.cs
  immichFrame.Web/package.json
  immichFrame.Web/src/lib/components/elements/asset-info.svelte
  immichFrame.Web/src/lib/components/elements/image-component.svelte
  immichFrame.Web/src/lib/components/elements/image.svelte
  immichFrame.Web/src/lib/components/elements/imageoverlay/image-overlay.svelte
  immichFrame.Web/src/lib/components/elements/imageoverlay/overlay-item.svelte
  immichFrame.Web/src/lib/components/elements/imageoverlay/overlay-qr.svelte
  immichFrame.Web/src/lib/components/elements/overlay-controls.svelte
  immichFrame.Web/src/lib/components/home-page/home-page.svelte
  immichFrame.Web/src/lib/immichFrameApi.ts
Labels: enhancement

#366 Fix: Appointment end time
  immichFrame.Web/src/lib/components/elements/appointments.svelte
Labels: fix

#361 Fix: Frameo WebView Fixes
  immichFrame.Web/src/lib/components/elements/appointments.svelte
  immichFrame.Web/src/lib/components/elements/clock.svelte
  immichFrame.Web/src/lib/components/elements/image-component.svelte
  immichFrame.Web/src/lib/components/elements/image.svelte
  immichFrame.Web/src/lib/components/elements/overlay-controls.svelte
  immichFrame.Web/src/lib/components/elements/progress-bar.svelte
  immichFrame.Web/src/lib/components/home-page/home-page.svelte
  immichFrame.Web/src/lib/hooks/useViewportHeight.ts
  immichFrame.Web/src/routes/+layout.svelte
  immichFrame.Web/tailwind.config.js
  immichFrame.Web/tailwind.plugins.ts
Labels: fix

#376 Chore: Cleanup fire-and-forget asset loading
  ImmichFrame.Core/Logic/OptimizedImmichFrameLogic.cs
Labels: maintenance
