Repository immichFrame/ImmichFrame, pull requests merged in 2025-06, with the labels that each got.

#377 Refactor: Use interface implementations in DI
  ImmichFrame.WebApi/Program.cs
Labels: maintenance

#379 Docs: Prettify the code-blocks on the apps.md page
  docs/docs/getting-started/apps.md
Labels: documentation

#380 Docs: Frameo webview update as list
  docs/docs/getting-started/apps.md
Labels: documentation

#390 Feat: Landscape split mode
  immichFrame.Web/src/lib/components/elements/image-component.svelte
  immichFrame.Web/src/lib/components/elements/image.svelte
  immichFrame.Web/src/lib/components/home-page/home-page.svelte
Labels: enhancement

#395 Chore: Update docusaurus to newest version
  docs/package-lock.json
  docs/package.json
Labels: maintenance

#391 Feat: Pan option
  ImmichFrame.Core/Interfaces/IClientSettings.cs
  ImmichFrame.WebApi/Models/WebClientSettings.cs
  docker/Settings.example.json
  docker/example.env
  docs/docs/getting-started/configuration.md
  docs/docs/getting-started/installation/docker.md
  immichFrame.Web/src/lib/components/elements/image-component.svelte
  immichFrame.Web/src/lib/components/elements/image.svelte
  immichFrame.Web/src/lib/components/home-page/home-page.svelte
  immichFrame.Web/src/lib/immichFrameApi.ts
Labels: enhancement

#374 Feat: Multiple Immich account support
  ImmichFrame.Core/Helpers/ApiCache.cs
  ImmichFrame.Core/Helpers/ListExtensionMethods.cs
  ImmichFrame.Core/ImmichFrame.Core.csproj
  ImmichFrame.Core/Interfaces/IClientSettings.cs
  ImmichFrame.Core/Interfaces/IImmichFrameLogic.cs
  ImmichFrame.Core/Interfaces/IServerSettings.cs
  ImmichFrame.Core/Logic/ImmichFrameLogic.cs
  ImmichFrame.Core/Logic/MultiImmichFrameLogicDelegate.cs
  ImmichFrame.Core/Logic/OptimizedImmichFrameLogic.cs
  ImmichFrame.Core/Logic/SimpleAccountSelectionStrategy.cs
  ImmichFrame.Core/Logic/TotalAccountImagesSelectionStrategy.cs
  ImmichFrame.Core/Services/IcalCalendarService.cs
  ImmichFrame.Core/Services/OpenWeatherMapService.cs
  ImmichFrame.WebApi.Tests/Helpers/Config/ConfigLoaderTest.cs
  ImmichFrame.WebApi.Tests/ImmichFrame.WebApi.Tests.csproj
  ImmichFrame.WebApi.Tests/Resources/TestV1.json
  ImmichFrame.WebApi.Tests/Resources/TestV2.json
  ImmichFrame.WebApi/Controllers/AssetController.cs
  ImmichFrame.WebApi/Controllers/ConfigController.cs
  ImmichFrame.WebApi/Helpers/Config/ConfigLoader.cs
  ImmichFrame.WebApi/Helpers/Config/ServerSettingsV1.cs
  ImmichFrame.WebApi/Helpers/ConfigLoader.cs
  ImmichFrame.WebApi/Helpers/ImmichFrameAuthenticationHandler.cs
  ImmichFrame.WebApi/ImmichFrame.WebApi.csproj
  ImmichFrame.WebApi/Models/ServerSettings.cs
  ImmichFrame.WebApi/Models/WebClientSettings.cs
  ImmichFrame.WebApi/Program.cs
  ImmichFrame.sln
  Install_Web.md
  docker/Settings.example.json
  docs/docs/getting-started/configuration.md
  docs/docs/getting-started/configurationV1.md
  docs/docs/getting-started/installation/docker.md
Labels: enhancement

#399 Maintenance: Add GitHub workflow to run tests
  .github/workflows/test.yml
Labels: maintenance

#400 Feat: Progressbar setting
  ImmichFrame.Core/Interfaces/IServerSettings.cs
  ImmichFrame.WebApi.Tests/Resources/TestV1.json
  ImmichFrame.WebApi.Tests/Resources/TestV2.json
  ImmichFrame.WebApi/Helpers/Config/ServerSettingsV1.cs
  ImmichFrame.WebApi/Models/ServerSettings.cs
  Install_Web.md
  docker/Settings.example.json
  docker/example.env
  docs/docs/getting-started/configuration.md
  immichFrame.Web/src/lib/components/home-page/home-page.svelte
  immichFrame.Web/src/lib/immichFrameApi.ts
Labels: enhancement

#412 Added ClientSettingsDto to expose subset of general settings in API
  ImmichFrame.WebApi/Controllers/ConfigController.cs
  ImmichFrame.WebApi/Models/ClientSettingsDto.cs
Labels: maintenance
