Repository immichFrame/ImmichFrame, pull requests merged in 2025-07, with the labels that each got.

#402 Feat: Support yaml config & Update Docs
  ImmichFrame.Core/Interfaces/IServerSettings.cs
  ImmichFrame.WebApi.Tests/Helpers/Config/ConfigLoaderTest.cs
  ImmichFrame.WebApi.Tests/ImmichFrame.WebApi.Tests.csproj
  ImmichFrame.WebApi.Tests/Resources/TestV1.json
  ImmichFrame.WebApi.Tests/Resources/TestV2.json
  ImmichFrame.WebApi.Tests/Resources/TestV2.yml
  ImmichFrame.WebApi/Helpers/Config/ConfigLoader.cs
  ImmichFrame.WebApi/Helpers/Config/ServerSettingsV1.cs
  ImmichFrame.WebApi/ImmichFrame.WebApi.csproj
  ImmichFrame.WebApi/Models/ClientSettingsDto.cs
  ImmichFrame.WebApi/Models/ServerSettings.cs
  ImmichFrame.WebApi/Program.cs
  Makefile
  docker/Settings.example.json
  docker/Settings.example.yml
  docker/example.env
  docs/docs/getting-started/configuration.md
  docs/docs/getting-started/installation/docker.md
  immichFrame.Web/src/lib/immichFrameApi.ts
Labels: enhancement

#423 Chore: Switched to IMemoryCache to correctly handle expiration
  ImmichFrame.Core.Tests/Logic/Pool/AlbumAssetsPoolTests.cs
  ImmichFrame.Core.Tests/Logic/Pool/AllAssetsPoolTests.cs
  ImmichFrame.Core.Tests/Logic/Pool/CachingApiAssetsPoolTests.cs
  ImmichFrame.Core.Tests/Logic/Pool/FavoriteAssetsPoolTests.cs
  ImmichFrame.Core.Tests/Logic/Pool/MemoryAssetsPoolTests.cs
  ImmichFrame.Core.Tests/Logic/Pool/PersonAssetsPoolTests.cs
  ImmichFrame.Core/Helpers/ApiCache.cs
  ImmichFrame.Core/Interfaces/IApiCache.cs
  ImmichFrame.Core/Logic/Pool/AlbumAssetsPool.cs
  ImmichFrame.Core/Logic/Pool/AllAssetsPool.cs
  ImmichFrame.Core/Logic/Pool/CachingApiAssetsPool.cs
  ImmichFrame.Core/Logic/Pool/FavoriteAssetsPool.cs
  ImmichFrame.Core/Logic/Pool/MemoryAssetsPool.cs
  ImmichFrame.Core/Logic/Pool/PeopleAssetsPool.cs
  ImmichFrame.Core/Logic/PooledImmichFrameLogic.cs
  ImmichFrame.Core/Services/IcalCalendarService.cs
  ImmichFrame.Core/Services/OpenWeatherMapService.cs
Labels: maintenance

#430 Fix: allow empty general settings
  ImmichFrame.WebApi.Tests/Helpers/Config/ConfigLoaderTest.cs
  ImmichFrame.WebApi.Tests/ImmichFrame.WebApi.Tests.csproj
  ImmichFrame.WebApi.Tests/Resources/TestV2_NoGeneral.json
  ImmichFrame.WebApi/Models/ServerSettings.cs
Labels: fix

#435 Docs: Update apps.md docs
  docs/docs/getting-started/apps.md
Labels: documentation

#424 Added ImmichServerUrl to AssetResponseDto
  ImmichFrame.Core/Api/AssetResponseDto.cs
  ImmichFrame.Core/Interfaces/IImmichFrameLogic.cs
  ImmichFrame.Core/Logic/AccountSelection/BloomFilterAssetAccountTracker.cs
  ImmichFrame.Core/Logic/AccountSelection/IAssetAccountTracker.cs
  ImmichFrame.Core/Logic/AccountSelection/TotalAccountImagesSelectionStrategy.cs
  ImmichFrame.Core/Logic/MultiImmichFrameLogicDelegate.cs
  ImmichFrame.Core/Logic/PooledImmichFrameLogic.cs
  ImmichFrame.WebApi/Program.cs
  immichFrame.Web/src/lib/components/elements/imageoverlay/image-overlay.svelte
  immichFrame.Web/src/lib/immichFrameApi.ts
Labels: fix

#441 Permit RefreshAlbumPeopleInterval of 0
  ImmichFrame.Core/Logic/PooledImmichFrameLogic.cs
Labels: fix

#425 Feat: Add AssetController test with direct settings DI
  ImmichFrame.Core/ImmichFrame.Core.csproj
  ImmichFrame.Core/Logic/PooledImmichFrameLogic.cs
  ImmichFrame.WebApi.Tests/Controllers/AssetControllerTests.cs
  ImmichFrame.WebApi.Tests/ImmichFrame.WebApi.Tests.csproj
  ImmichFrame.WebApi.Tests/Mocks/MockHttpMessageHandler.cs
  ImmichFrame.WebApi/Controllers/AssetController.cs
  ImmichFrame.WebApi/Program.cs
Labels: enhancement
