Repository immichFrame/ImmichFrame, pull requests merged in 2025-01, with the labels that each got.

#247 iOS PWA support
  immichFrame.Web/src/app.html
Labels: enhancement

#257 Calendar fix
  immichFrame.Web/src/lib/components/elements/appointments.svelte
Labels: fix

#254 Feat: Custom CSS support
  ImmichFrame.WebApi/ImmichFrame.WebApi.csproj
  ImmichFrame.WebApi/Program.cs
  ImmichFrame.WebApi/wwwroot/static/custom.css
  docker/docker-compose.yml
  immichFrame.Web/src/lib/components/elements/appointments.svelte
  immichFrame.Web/src/lib/components/elements/asset-info.svelte
  immichFrame.Web/src/lib/components/elements/clock.svelte
  immichFrame.Web/src/lib/components/elements/image-component.svelte
  immichFrame.Web/src/lib/components/elements/image.svelte
  immichFrame.Web/src/lib/components/elements/overlay-controls.svelte
  immichFrame.Web/src/lib/components/elements/progress-bar.svelte
  immichFrame.Web/src/lib/components/elements/thumbHashImage.svelte
  immichFrame.Web/src/routes/+layout.svelte
  immichFrame.Web/vite.config.ts
Labels: ImmichFrame_Web

#258 Feat: Add authentication via basic secret
  ImmichFrame.Core/Interfaces/IServerSettings.cs
  ImmichFrame.WebApi/Controllers/AssetController.cs
  ImmichFrame.WebApi/Controllers/CalendarController.cs
  ImmichFrame.WebApi/Controllers/ConfigController.cs
  ImmichFrame.WebApi/Controllers/WeatherController.cs
  ImmichFrame.WebApi/Helpers/CustomAuthenticationMiddleware.cs
  ImmichFrame.WebApi/Helpers/ImmichFrameAuthenticationHandler.cs
  ImmichFrame.WebApi/Models/ServerSettings.cs
  ImmichFrame.WebApi/Program.cs
  Install_Web.md
  README.md
  docker/Settings.example.json
  docker/example.env
  immichFrame.Web/src/lib/components/elements/appointments.svelte
  immichFrame.Web/src/lib/components/elements/clock.svelte
  immichFrame.Web/src/lib/components/elements/error-element.svelte
  immichFrame.Web/src/lib/components/elements/image-component.svelte
  immichFrame.Web/src/lib/components/home-page/home-page.svelte
  immichFrame.Web/src/lib/immichFrameApi.ts
  immichFrame.Web/src/lib/index.ts
  immichFrame.Web/src/lib/stores/persist.store.ts
Labels: ImmichFrame_Web

#260 Fix: Immich Api Changes
  ImmichFrame.Core/ImmichFrame.Core.csproj
  ImmichFrame.Core/Logic/ImmichFrameLogic.cs
  ImmichFrame.Core/OpenAPIs/immich-openapi-specs.json
Labels: fix
