Repository immichFrame/ImmichFrame, pull requests merged in 2025-02, with the labels that each got.

#272 handle quotes for PhotoDateFormat in API
  ImmichFrame.WebApi/Controllers/AssetController.cs
Labels: bug

#278 Add invoke to GetWeather timer, simplify time interval
  immichFrame.Web/src/lib/components/elements/clock.svelte
Labels: fix

#277 Feat: Multiday handling for calendar appointments
  immichFrame.Web/src/lib/components/elements/appointments.svelte
Labels: ImmichFrame_Web
